toss/overlay-kit

packages/package.json, packages/src/utils/create-use-external-events.ts, packages/src/utils/emitter.ts, yarn.lock
Zero dependency could be much better for library users if we could
=> refactor: remove mitt

packages/src/context/context.test.tsx
add test useOverlayContext unmountAll
=> test: useOverlayContext unmountAll

packages/src/context/context.test.tsx
add useOverlayList test code
I'll help you achieve 100% coverage !
=> test: add useOverlayList test code

packages/src/context/context.test.tsx, packages/src/context/provider.tsx, packages/src/event.test.tsx, packages/src/utils/create-safe-context.ts, packages/src/utils/create-use-external-events.test.ts, packages/src/utils/create-use-external-events.ts
=> fix: update Korean to English

docs/installation.md, docs/ko/installation.md
AS mentioned by @manudeli, in https://github.com/toss/overlay-kit/pull/23#pullrequestreview-2150074760
I update docs
close: #24
=> docs: update version notification of react

docs/ko/installation.md
I found some untranslated parts and fixed them.
=> docs: ko translation installation.md

docs/ko/usage/custom-id.md, docs/usage/custom-id.md, packages/src/event.ts
=> feat: Add overlay custom id

.changeset/poor-cougars-grow.md, .github/pull_request_template.md
- Added a pull request template to standardize PR descriptions
- Includes sections for description, changes, motivation, testing, and checklist
- Ensures all necessary information is provided for each PR
This template helps maintain consistency and clarity in PR submissions.
=> chore: Add pull request template

packages/src/context/reducer.ts
**Related Issue:** [Comment](https://github.com/toss/overlay-kit/pull/50#discussion_r1676997111) (issue_number)
I fix comment. `close 2` -> `close 3`
X
X
X
=> docs: fix comment

docs/ko/quickstart.md
update ko docs ko/quickstart.md
=> docs(quickstart): Update ko docs ko/quickstart.md

docs/advanced/promise.md, docs/reference/overlay.md
Corrected the typo in the English document.
=> docs: fix typo

docs/introduction.md
주어가 단수인 logic이므로 be동사도 생략하고 spreads로 수정되어야 자연스러울 것 같습니다.
are spread -> spreads
=> docs: fix grammatical error

docs/installation.md, docs/ko/installation.md
The pnpm official documentation recommends using the `add` command instead of `install` when installing new packages as follows:
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
Currently it works the same without any differences, but the document clearly distinguishes these two commands.
This means that you have the flexibility to adapt to changes, such as changing or removing commands in future versions.
=> docs: replace `pnpm install` with `pnpm add`

packages/src/event.test.tsx
this change replaces arrow functions with named functions. the project predominantly uses named function syntax, and this modification ensures consistency throughout the codebase.
* changed the wrapper function from an arrow function to a named function.
* changed the `renderWithUser` function from an arrow function to a named function.
* updated the `Component` definitions in test cases to use named functions.
to align with the existing code style, which primarily uses named functions, this change promotes consistency across the project. this adjustment improves code readability and ensures adherence to the project’s coding conventions, ultimately benefiting team collaboration.
* unit testing: verified that all existing tests pass successfully using `@testing-library/react` and `vitest`. …
=> test(packages/event.test.tsx): refactor arrow function to named function for consistency

.changeset/ten-geckos-type.md, packages/package.json
=> fix: update pkg.repository.url

.changeset/spicy-carrots-attack.md, packages/package.json
=> feat: esm first (support cjs by exports field of package.json)

.yarnrc.yml, docs/next.config.mjs, docs/package.json, docs/src/components/main.tsx, docs/src/pages/ko/_meta.tsx, docs/src/pages/ko/index.mdx, docs/theme.config.tsx, eslint.config.cjs, examples/react-16/framer-motion/src/components/modal.tsx, examples/react-16/framer-motion/src/main.tsx, yarn.lock
Mobile size design also needs to be worked on.
=> docs: main page

docs/theme.config.tsx
add footer content (reference to suspensive)
add footer content (MIT 2025 © Viva Republica, Inc.)
Footer shows nextra related content.
You can check the correct footer by accessing localhost:3000 using the `yarn dev` command.
=> docs: add footer content

docs/src/pages/en/api/index.mdx, docs/src/pages/ko/api/index.mdx
**Related Issue:** N/A
- Removed unused `References` page.
- https://overlay-kit.slash.page/ko/api and https://overlay-kit.slash.page/en/api is broken.
N/A
N/A
=> docs: remove empty API reference pages

README-ko_kr.md, README.md, docs/src/pages/en/docs/guides/_meta.tsx, docs/src/pages/en/docs/guides/code-comparison.mdx, docs/src/pages/ko/docs/guides/_meta.tsx, docs/src/pages/ko/docs/guides/code-comparison.mdx
**Related Issue:** Fixes #110 
- Duped old document to new docs route.
- Add Korean translation
- Fix links in `README.md`
- The link in the main part of repository home is broken. So I thought I have to fix it.
=> fix(docs): Move old docs to new one and fix broken link

docs/theme.config.tsx
This PR adds a Discord server link to the documentation theme configuration.
- Added a chat configuration with Discord server link to the documentation theme configuration file (docs/theme.config.tsx)
- The link points to the dedicated Discord server: https://discord.gg/vGXbVjP2nY
=> docs: Add Discord community chat link to docs theme config

docs/theme.config.tsx
Updated the default description of overlay-kit in the documentation theme configuration to better reflect the library's primary purpose and functionality.
=> docs: Update description

README-ko_kr.md, README.md
=> docs: Update readme

packages/src/index.ts
This PR exports additional type definitions from the content-overlay-controller module, specifically `OverlayControllerComponent` and `OverlayAsyncControllerComponent` types.
This change improves type accessibility for external consumers of the package.
- Added type exports for `OverlayControllerComponent` and `OverlayAsyncControllerComponent`
The types were previously only available internally within the package.
External consumers needed access to these types for proper type checking and development experience.
- Verified that the types are properly exported and accessible when importing from the package
This change is purely additive and does not affect existing functionality.
It only exposes previously internal types for better developer …
=> feat: export types from content-overlay-controller

docs/src/components/sandpack/base-template.ts
This pull request addresses a compatibility issue that occurred due to mismatched versions between @mui/material and @mui/utils. Specifically, when upgrading @mui/material to version 7.0.0, the @mui/utils module could not be found, leading to errors in the application.
**Related Issue:** Fixes #133 
- Downgraded @mui/material to version 6.x.x in the base-template.ts file to ensure compatibility with @mui/utils.
The update to @mui/material version latest caused issues because it was incompatible with the existing version of @mui/utils. This change fixes the missing module error and ensures that the application runs without issues related to these dependencies.
I have tested the changes locally by modifying the dependencies as described. After making the necessary updates to the …
=> fix: specify version for @mui/material dependency
