toss/overlay-kit

packages/src/context/context.test.tsx
Change the description of the test code correctly.
=> test: Change 'overlay.exit' to 'overlay.unmount' correctly

docs/ko/quickstart.md
Made `<OverlayProvider />` visible by fixing typo in Korean document.
=> docs: make `<OverlayProvider />` visible in Korean document

packages/src/context/context.ts, packages/src/utils/create-use-external-events.ts
Previously `createEvent` function used a _hacky_ method to make a parameter optional when it had `undefined` in its `payload`.
However, this method made TypeScript unable to infer the names of the parameters correctly.
This resulted in issues such as:
```ts
overlay.close(payload_0: string)
overlay.closeAll(payload_0?: undefined)
```
TypeScript inferred the parameters as `payload_0: string` or `payload_0?: undefined`, which is not ideal.
To resolve this, changes were made so that TypeScript can correctly infer the parameter types alongside the inserted `EventKey`.
After the changes, the parameter types are correctly inferred as:
```ts
overlay.close(overlayId: string)
overlay.closeAll()
```
Now, it appears the same as the documentation. The documentation correctly showed …
=> chore: edit `createEvent` to infer parameter type of return function

packages/src/event.test.tsx, packages/src/utils/create-use-external-events.test.ts
This PR fixes minor typo in `event.test.tsx` and `create-use-external-events.ts`.
The `describe` in `event.test.tsx` should have describe `overlay` object, not `useOverlayContext`. And same applies to `createUseExternalEvents`.
=> chore: edit `describe` in `event.test.tsx` and `create-use-external-events.ts`

packages/src/index.ts
This PR restricts exports from `src/index.ts`. Previous codebase was exporting internal functions or hooks such as `createEvent`, `useOverlayList` or `useOverlayEvent`, which should not be accessible from outside of the module.
=> fix: fixed incorrect export from `index.ts`

eslint.config.cjs, examples/framer-motion/src/components/modal.tsx, packages/src/context/context.ts, packages/src/context/provider.tsx, packages/src/context/reducer.ts, packages/src/event.ts
"type import" is being used, but "human error" is visible. Complement by adding "ESLint" rule.
You can refer to [this link](https://typescript-eslint.io/rules/consistent-type-imports/).
=> refactor(overlay-kit): add type import ESLint rule

docs/installation.md, docs/ko/installation.md
I update installation section with vitepress api
- Add Prerequisites
- combine Nodejs with bun with code-group
preview
=> docs: update install section

docs/ko/quickstart.md
I saw some typo at korean docs
eng ver is...
=> docs: typo at ko quickstart

docs/.vitepress/en.mts, docs/.vitepress/ko.mts
I think the custom ID feature was added, but I couldn't find it in the documentation.
So I add sidebar link.
=> docs: add custom-id sidebar

.changeset/soft-jokes-move.md, packages/src/context/reducer.ts
=> fix: Set current to null if no overlay remains on unmount

.changeset/new-dodos-watch.md, packages/src/event.ts
close #38 
Rename it for consistency.
`id` => `overlayId`
=> chore: rename to overlayId

packages/src/event.test.tsx
When I tried to add test code, the old test dependencies were left behind 😂.
**event.test.tsx**
```tsx
... // Existing code
// Test code to add
it('test', () => {
const wrapper = ({ children }: PropsWithChildren) => <OverlayProvider>{children}</OverlayProvider>;
const Component = () => {
const overlayData = useOverlayData();
console.log(overlayData);
return null;
};
const renderComponent = render(<Component />, { wrapper });
});
```
To solve this, I added the following code
```tsx
afterEach(() => {
overlay.unmountAll();
});
```
=> test: add afterEach unmountAll()

.changeset/shaggy-scissors-refuse.md, packages/src/context/reducer.ts
=> Change current value when closing overlay

.changeset/quiet-bobcats-pretend.md, packages/src/context/reducer.ts
This PR addresses an issue where the 'current' overlay does not update to the last overlay when an intermediate overlay is closed. This behavior can lead to inconsistencies in the UI state.
- Modified the reducer logic to ensure 'current' is correctly set to the last overlay when closing an intermediate overlay.
- Added checks to handle cases where the overlay order is modified.
The previous implementation did not account for scenarios where closing an intermediate overlay should update the 'current' overlay to reflect the last one in the order. This fix ensures that the 'current' overlay always points to the last opened overlay, maintaining consistent UI behavior.
- Tested by manually opening and closing multiple overlays in various orders to ensure 'current' updates correctly.
- I plan …
=> Fix: Update 'current' to Reflect Last Overlay When Closing Intermediate Overlays

.changeset/tall-flowers-trade.md, packages/src/context/provider.tsx, packages/src/context/reducer.ts
This change enhances the overlay state management to ensure overlays maintain the correct state when closed and reopened, and prevents duplicate overlay entries. It addresses issues with the overlay's `current` state not updating correctly in certain scenarios.
**Related Issue:** Fixes #46 
- Added `current` state to track the current overlay in `OverlayProvider` and `ContentOverlayController`.
- Implemented logic in `ContentOverlayController` to maintain overlay state correctly when an overlay is closed and reopened without unmounting.
- Updated `ContentOverlayController` to use `useRef` for tracking the previous `current` state and triggering the `onMounted` callback appropriately.
- Improved type definitions for `ContentOverlayControllerProps` and `OverlayControllerProps` to include …
=> fix: Enhance Overlay State Management and Prevent Duplicate Entries

.changeset/tricky-grapes-bake.md, packages/src/context/reducer.ts
This change fixes an issue where overlays did not retain their state when reopened without unmounting, even though they were not removed from the DOM. The overlayReducer has been updated to maintain the state of overlays between close and open cycles, addressing an unintended state reset.
**Related Issue:** Fixes #57 
- Modified the overlayReducer to check if an overlay exists before updating its state in `overlayData`. If the overlay exists, its state is retained.
- Ensured that overlays do not reset their state upon reopening unless explicitly re-initialized or unmounted.
This change is necessary to ensure that the overlay components behave as expected across user interactions.
- Tested by manually reopening overlays without unmounting them to ensure their state is maintained. …
=> fix: state reset issue on overlay reopen

.changeset/brown-boxes-wink.md, packages/src/context/provider.tsx
This commit adds a useEffect cleanup function to the OverlayProvider component that dispatches a ‘REMOVE_ALL’ action upon unmounting. This ensures that overlays are properly cleaned up during testing scenarios, preventing state leakage and side effects from persistent overlays.
This commit introduces a useEffect cleanup function in the OverlayProvider component that dispatches a 'REMOVE_ALL' action when the component unmounts.
This change ensures that all overlays are properly cleaned up during testing scenarios, preventing state leakage and side effects from persistent overlays.
**Related Issue:** Fixes #63
- Added a useEffect cleanup function in `OverlayProvider` to dispatch 'REMOVE_ALL' on unmount.
This change is necessary to enhance the testability of the OverlayProvider by ensuring …
=> feat: Add cleanup effect for unmounting

packages/package.json, packages/src/event.test.tsx, yarn.lock
Perform the migration to userEvent described in issue number 68.
**Related Issue:** Fixes #68
- All changes occurred only in testcode
- add devDependencies @testing-library/user-event , @testing-library/dom
before
```tsx
const renderComponent = render(<Component />, { wrapper });
const testContentElement = await renderComponent.findByText(testContent);
act(() => {
testContentElement.click();
});
const dialogContentElement = await renderComponent.findByText(dialogContent);
act(() => {
dialogContentElement.click();
});
await waitFor(() => {
expect(mockFn).toHaveBeenCalledWith(true);
});
```
after
```tsx
const { user } = renderWithUser(<Component />);
await user.click(await screen.findByRole('button', { name: overlayTriggerContent }));
await user.click(await screen.findByRole('button', { …
```
=> refactor: Migrate overlay-kit test code act to userEvent

.changeset/rich-otters-fry.md, examples/react-16/framer-motion/package.json, examples/react-17/framer-motion/package.json, packages/src/context/use-sync-overlay-store.ts, yarn.lock
The import path for `use-sync-external-store/shim` was incorrect, causing a path resolution error during build. This change updates the import statement to include `index.js`, resolving the path issue.
- Updated the import statement in `use-sync-overlay-store.ts` to `use-sync-external-store/shim/index.js`.
This change is necessary to resolve a path resolution error that was preventing the build process from completing successfully. By specifying the correct import path, we ensure that the required module is correctly located and imported.
- Verified that the application builds successfully after the change.
- Tested the functionality that depends on `use-sync-external-store` to ensure it works as expected.
=> fix: path resolution error by updating

eslint.config.cjs
this pr removes the usage of `eslint-config-prettier` from `eslint.config.cjs` and adds `eslint-plugin-prettier`.
the `eslint-config-prettier` library itself is not deleted, as it is required for `eslint-plugin-prettier` to function correctly.
* `eslint-config-prettier` disables eslint rules that conflict with prettier.
* `eslint-plugin-prettier` enforces prettier rules within eslint, providing a seamless integration. however, it depends on `eslint-config-prettier` to handle conflict resolution.
* `eslint-config-prettier` remains as a dependency, ensuring compatibility.
* `eslint-plugin-prettier` is added to integrate prettier rules directly into eslint, improving developer experience.
* removed `eslint-config-prettier` usage from `eslint.config.cjs`
* added `eslint-plugin-prettier` to …
=> chore(eslint.config.cjs): replace eslint-config-prettier with eslint-plugin-prettier

.github/workflows/ci.yml, README-ko_kr.md, README.md, codecov.yml, examples/react-16/framer-motion/package.json, examples/react-16/framer-motion/src/demo.tsx, examples/react-16/framer-motion/src/main.tsx, examples/react-16/framer-motion/tsconfig.json, examples/react-17/framer-motion/package.json, examples/react-17/framer-motion/src/demo.tsx, examples/react-17/framer-motion/src/main.tsx, examples/react-17/framer-motion/tsconfig.json, examples/react-18/framer-motion/package.json, examples/react-18/framer-motion/src/demo.tsx, examples/react-18/framer-motion/src/main.tsx, examples/react-18/framer-motion/tsconfig.json, packages/.gitignore, packages/README.md, packages/package.json, packages/vitest.config.mts, yarn.lock
=> chore: add ci action

.changeset/evil-donuts-fold.md, packages/src/context/provider/content-overlay-controller.tsx, packages/src/context/reducer.ts
**Related Issue:** Fixes N/A
- Add checks to prevent unnecessary state updates for non-existent or already open/closed overlays
- Handle edge cases like closing all overlays when no overlays exist
- Defence logic moved into reducer, thus I removed `isOpen === false` clause from `ContentOverlayController`
- Tested manually to ensure it works the same as before
=> fix: Enhance overlay reducer state management

docs/src/pages/en/docs/guides/introduction.mdx, docs/src/pages/ko/docs/guides/introduction.mdx
This PR updates the usage example of overlay.openAsync to include a tri-state pattern: true, false, and null (representing “not selected”).
**Related Issue:** Fixes #142 
- Updated example code to initialize the result state as null instead of false
- Modified the UI to display "Not selected" when result is null
- Improved clarity in differentiating between:
- User confirming (true)
- User canceling (false)
- User not having selected anything yet (null)
The current example initializes the result as false, which causes the UI to display "N" even when the user hasn't made any selection yet. This leads to ambiguity in interpreting the user's intent.
By introducing an initial null state and displaying "Not selected" accordingly, this change improves UX clarity and demonstrates a more flexible …
=> fix: tri-state pattern (including "not selected") in official usage of overlay.openAsync

.changeset/early-ducks-hang.md, packages/src/utils/create-safe-context.ts
This pull request addresses the unnecessary type casting in the createSafeContext function. The Context.Provider is already correctly typed as T | typeof NullSymbol, so casting it to Provider<T> is redundant and unnecessary. This change improves code readability and maintains type safety without unnecessary type assertions.
- Removed the unnecessary type casting of Context.Provider to Provider<T> in the createSafeContext function.
- Simplified the type declaration to ensure the code is cleaner and easier t
This change was made to improve the maintainability of the code. By removing unnecessary type casting, we reduce complexity and make the codebase easier to understand. It's a best practice to avoid redundant type assertions, as they can lead to confusion and errors in the long run.
The …
=> fix: remove unnecessary type assertion from Context.Provider

.changeset/forty-apes-decide.md, packages/src/context/provider/content-overlay-controller.tsx, packages/src/context/provider/index.tsx, packages/src/context/reducer.ts
This PR optimizes overlay controller performance by preventing unnecessary re-renders of existing overlays when new overlays are opened.
The solution integrates React.memo to prevent re-rendering and streamlines state management by integrating it directly into the component.
- **Why is this change required?** Currently, when a new overlay is opened, all existing overlays re-render unnecessarily, causing performance issues.
- **What problem does it solve?** Eliminates unnecessary re-renders of existing overlays, improving application performance and user experience.
- **Dependencies:** No additional dependencies required.
- Added React.memo to overlay controller component to prevent unnecessary re-renders
- Integrated state management directly into …
=> fix: prevent unnecessary re-renders of existing overlays with memo

.changeset/tiny-pots-fail.md, packages/src/context/provider/content-overlay-controller.tsx, packages/src/context/provider/index.tsx, packages/src/context/reducer.ts, packages/src/event.test.tsx
This PR fixes a bug where overlays could not be reopened after being closed when using the same overlay ID. The issue occurred because the overlay state management didn't properly handle the case where an overlay was closed and then reopened with the same identifier.
**Related Issue:** Fixes #186
- Added `isMounted` property to `OverlayItem` type to track overlay mounting state
- Modified the `ADD` action in reducer to handle reopening of existing closed overlays
- Added state comparison logic in `OverlayProvider` to detect overlay state changes and trigger proper reopening
- Updated `OPEN` action to set `isMounted: true` when opening overlays
- Added `useRef` to track previous overlay state for comparison
- Restructured overlay controller props order and import statements for consistency …
=> fix: enable reopening overlay after `close()` with `overlay.open`

docs/src/pages/en/api/utils/overlay-close-all.mdx, docs/src/pages/ko/api/utils/overlay-close-all.mdx
This PR fixes the documentation of the overlay.closeAll function by correcting a mistaken reference to `overlay.close()` and replacing it with the correct `overlay.closeAll()`. This change is required to prevent user confusion and ensure that the documentation accurately reflects the intended function to be called when closing all overlays.
- Corrected the reference from `overlay.close()` to `overlay.closeAll()` in the References section and other relevant parts of the overlay.closeAll documentation.
- Updated code examples to consistently use `overlay.closeAll()` where all overlays are being closed.
The incorrect reference to `overlay.close()` in the overlay.closeAll documentation could mislead users into calling the wrong method when intending to close all active overlays. This update …
=> docs: correct `overlay.close()` to `overlay.closeAll()` in overlay.closeAll documentation
